version: "3.8"
services: 
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    ports: 
    - "27017:27017"
    volumes: 
    - ./backend/data:/data

  backend:
    container_name: backend_container
    build: ./backend
    env_file: ./backend/.env.docker
    ports: 
    - 8041:8080 
    depends_on:
      - mongodb


  frontend: 
    container_name: frontend_container 
    build: ./frontend
    env_file: ./frontend/.env.docker 
    ports:
    - "5173:5173"

